export const REQ_BODY = {
  LOG_Id: 0,
  LOG_SubMenuId: 0,
  SubMenu: {
    SBM_Id: 0,
    SBM_MenuId: 0,
    Menu: {
      MEN_Id: 0,
      MEN_Nome: "string",
      MEN_Codigo: "string",
      MEN_Ativo: true,
      MEN_Ordem: 0,
      MEN_Icone: "string",
      MEN_FLAGMOBILE: true,
      Log: {},
    },
    SBM_Nome: "string",
    SBM_Descricao: "string",
    SBM_Codigo: "string",
    SBM_Controller: "string",
    SBM_Ordem: 0,
    SBM_Ativo: true,
    SBM_FLAGMOBILE: true,
    SBM_Icone: "string",
    Log: {},
  },
  LOG_UsuarioId: 0,
  Usuario: {
    USR_Id: 0,
    USR_Email: "string",
    USR_Senha: "string",
    USR_Ativo: true,
    USR_PessoaId: 0,
    Pessoa: {
      PES_Id: 0,
      PES_Nome: "string",
      PES_SexoId: 0,
      Sexo: {
        SEX_Id: 0,
        SEX_Nome: "string",
        SEX_Sigla: "string",
        SEX_Ativo: true,
        Log: {},
      },
      PES_CPF: "string",
      PES_DataNascimento: "2022-02-21T13:46:35.878Z",
      PES_Ativo: true,
      PES_RG: "string",
      PES_EnderecoId: 0,
      Endereco: {
        END_Id: 0,
        END_Logradouro: "string",
        END_Numero: 0,
        END_Bairro: "string",
        END_Cidade: "string",
        END_Estado: "string",
        END_Complemento: "string",
        END_CEP: "string",
        END_CidadeId: 0,
        Cidade: {
          CDD_Id: 0,
          CDD_Nome: "string",
          CDD_EstadoId: 0,
          Estado: {
            ESD_Id: 0,
            ESD_Nome: "string",
            ESD_Sigla: "string",
            ESD_Ativo: true,
            Log: {},
          },
          CDD_CepInicial: "string",
          CDD_CepFinal: "string",
          CDD_FlgNaturalidade: true,
          CDD_Ativo: true,
          Log: {},
        },
        END_EstadoId: 0,
        Estado: {
          ESD_Id: 0,
          ESD_Nome: "string",
          ESD_Sigla: "string",
          ESD_Ativo: true,
          Log: {},
        },
        END_Latitude: 0,
        END_Longitude: 0,
        END_Ativo: true,
        END_Regiao: "string",
        END_CodIBGE: "string",
        Log: {},
      },
      PES_EnderecoFoto: "string",
      PES_TelefoneResidencial: "string",
      PES_Celular: "string",
      PES_Email: "string",
      PES_SexoBiologico: "string",
      PES_PronomeTratamentoId: 0,
      PronomeTratamento: {
        PRT_Id: 0,
        PRT_Nome: "string",
        PRT_Descricao: "string",
        PRT_Ativo: true,
        Log: {},
      },
      PES_Renda: 0,
      Log: {},
    },
    USR_UnidadeId: 0,
    USR_PrimeiroAcesso: true,
    USR_DeviceID: "string",
    USR_TokenRecoveryPassword: "string",
    USR_TokenDateExpire: "2022-02-21T13:46:35.878Z",
    Log: {},
    sucesso: true,
    mensagemSucesso: "string",
    perfilxUsuario: {
      PXU_Id: 0,
      PXU_UsuarioId: 0,
      Usuario: {},
      PXU_PerfilId: 0,
      Perfil: {
        PRF_Id: 0,
        PRF_UnidadeId: 0,
        PRF_Descricao: "string",
        PRF_Nome: "string",
        PRF_Ativo: true,
        Log: {},
      },
      PXU_Ativo: true,
      Log: {},
    },
    perfilxSubMenu: {
      PXS_Id: 0,
      PXS_SubMenuId: 0,
      SubMenu: {
        SBM_Id: 0,
        SBM_MenuId: 0,
        Menu: {
          MEN_Id: 0,
          MEN_Nome: "string",
          MEN_Codigo: "string",
          MEN_Ativo: true,
          MEN_Ordem: 0,
          MEN_Icone: "string",
          MEN_FLAGMOBILE: true,
          Log: {},
        },
        SBM_Nome: "string",
        SBM_Descricao: "string",
        SBM_Codigo: "string",
        SBM_Controller: "string",
        SBM_Ordem: 0,
        SBM_Ativo: true,
        SBM_FLAGMOBILE: true,
        SBM_Icone: "string",
        Log: {},
      },
      PXS_PerfilId: 0,
      Perfil: {
        PRF_Id: 0,
        PRF_UnidadeId: 0,
        PRF_Descricao: "string",
        PRF_Nome: "string",
        PRF_Ativo: true,
        Log: {},
      },
      PXS_Ativo: true,
      Log: {},
    },
    USR_AceitouTermoUso: true,
    USR_AceitouPolitica: true,
    USR_FlagGestor: true,
    USR_FlagContratante: true,
    USR_FlagProfissional: true,
    USR_DataLeituraAvisoCorona: "2022-02-21T13:46:35.878Z",
  },
  LOG_DataHora: "2022-02-21T13:46:35.878Z",
  LOG_Token: "string",
  LOG_IpEstacao: "string",
  LOG_Observacao: "string",
  LOG_TipoTransacaoId: 0,
  TipoTransacaoLog: {
    TTL_Id: 0,
    TTL_Nome: "string",
    TTL_Descricao: "string",
    TTL_Ativo: true,
    Log: {},
  },
  LOG_Ativo: true,
  LOG_PlataformaId: 0,
  LOG_VersaoPlataforma: "string",
  LOG_VersaoApi: "string",
  LOG_PerfilId: 0,
  Perfil: {
    PRF_Id: 0,
    PRF_UnidadeId: 0,
    PRF_Descricao: "string",
    PRF_Nome: "string",
    PRF_Ativo: true,
    Log: {},
  },
  LOG_Metodo: "string",
  LOG_ParametroJson: "string",
  LOG_UnidadeId: 0,
  LOG_QueryString: "string",
  LOG_InternoSympor: true,
  LOG_EstabelecimentoId: 0,
};

export const CASOS_DUMMY_DATA = [
  {
    CAS_Id: 1,
    CAS_NumeroSolicitacao: "0000010000",
    CAS_PacienteId: 184,
    Paciente: {
      PAC_Id: 184,
      PAC_UsuarioId: 578,
      Usuario: null,
      PAC_Ativo: true,
      PAC_Prontuario: "123",
      PAC_ObservacaoClinica: "asdasdas",
      PAC_OperadoraId: 6,
      PAC_NumeroCarteirinha: "0181061170000200",
      PAC_DataCriacao: "2021-01-10T00:00:00",
      Log: null,
    },
    CAS_TipoCasoId: 0,
    TipoCaso: {
      TPC_Id: 0,
      TPC_Descricao: "Cirurgia",
      TPC_Ativo: true,
      Log: null,
    },
    CAS_StatusCasoId: 1,
    StatusCaso: {
      STC_Id: 1,
      STC_Descricao: "Em Análise",
      STC_Ativo: true,
      Log: null,
    },
    CAS_HospitalId: 2,
    Hospital: {
      HOS_Id: 2,
      HOS_EnderecoId: 634,
      Endereco: null,
      HOS_TelefonePS: "11999999999",
      HOS_TelefonePSRamal: null,
      HOS_TelefoneOnco: null,
      HOT_TelefoneOncoRamal: null,
      HOS_Ativo: true,
      HOS_FlagFavorito: false,
      HOS_EnfermeiroReferencia: null,
      HOS_Nome: "Mauricio Teste_1501",
      Log: null,
    },
    CAS_ProcedimentoId: 1,
    Procedimento: {
      PRO_Id: 1,
      PRO_UsuarioCriacaoId: 1,
      UsuarioCriacao: null,
      PRO_UsuarioAlteracaoId: 1,
      UsuarioAlteracao: null,
      PRO_Codigo: "001",
      PRO_Nome: "Outras",
      PRO_Descricao: "Outras",
      PRO_DataCriacao: "2022-01-28T19:51:13.5",
      PRO_DataAlteracao: "2022-01-28T19:53:13.5",
      PRO_Ativo: true,
      Log: null,
    },
    CAS_DescricaoProcedimento: "Procedimento Teste",
    CAS_DescricaoCaso: "Caso Teste Cirurgia",
    CAS_DescricaoAvaliador:
      '<p style="text-align:right;">direita</p><p style="text-align:right;"><br /></p><p style="text-align:left;"><u>sublinhado</u></p><p style="text-align:center;"><strong>negrito center</strong></p><p style="text-align:left;"><span style="color:#E53333;">vermelho</span></p><p style="text-align:left;"><span><em>italico</em></span></p><p style="text-align:left;"><br /></p><ol><li><span><em>item 1</em></span></li><li><span><em>item 2</em></span></li></ol><p><br /></p><p style="text-align:left;"><br /></p><ul><li><span>marc a</span></li><li><span>marc b</span></li><li><span>marc c</span></li></ul><p><span style="font-size:18px;">tamanho grande</span></p><p><span style="font-size:18px;"><br /></span></p><p style="text-align:justify;"><span style="font-size:18px;"><strong>Lorem Ipsum</strong><span style="font-family:&quot;font-size:14px;background-color:#FFFFFF;">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br /></span></p><p><br /></p><p style="text-align:left;"><span style="color:#E53333;"><br /></span></p>',
    CAS_DataAvaliacao: "2022-02-15T21:01:15.57",
    CAS_UsuarioAvaliacaoId: 565,
    UsuarioAvaliacao: {
      USR_Id: 565,
      USR_Email: "avaliador@gmail.com",
      USR_Senha: "waZoWtWDZuc=",
      USR_Ativo: true,
      USR_PessoaId: 559,
      Pessoa: null,
      USR_UnidadeId: 0,
      USR_PrimeiroAcesso: true,
      USR_DeviceID: null,
      USR_TokenRecoveryPassword: "565-445002",
      USR_TokenDateExpire: "2020-12-02T14:54:50.753",
      Log: null,
      sucesso: false,
      mensagemSucesso: null,
      perfilxUsuario: null,
      perfilxSubMenu: null,
      USR_AceitouTermoUso: null,
      USR_AceitouPolitica: null,
      USR_FlagGestor: false,
      USR_FlagContratante: false,
      USR_FlagProfissional: true,
      USR_DataLeituraAvisoCorona: "2021-06-08T22:18:02.167",
    },
    CAS_Valor: 123.45,
    CAS_DataCriacao: "2022-01-28T20:05:04.45",
    CAS_Ativo: true,
    ListaDocumentos: null,
    tipo: 0,
    Log: null,
  },
  {
    CAS_Id: 2,
    CAS_NumeroSolicitacao: "0000010001",
    CAS_PacienteId: 184,
    Paciente: {
      PAC_Id: 184,
      PAC_UsuarioId: 578,
      Usuario: null,
      PAC_Ativo: true,
      PAC_Prontuario: "123",
      PAC_ObservacaoClinica: "asdasdas",
      PAC_OperadoraId: 6,
      PAC_NumeroCarteirinha: "0181061170000200",
      PAC_DataCriacao: "2021-01-10T00:00:00",
      Log: null,
    },
    CAS_TipoCasoId: 1,
    TipoCaso: {
      TPC_Id: 1,
      TPC_Descricao: "Exame",
      TPC_Ativo: true,
      Log: null,
    },
    CAS_StatusCasoId: 0,
    StatusCaso: {
      STC_Id: 0,
      STC_Descricao: "Analisar",
      STC_Ativo: true,
      Log: null,
    },
    CAS_HospitalId: 2,
    Hospital: {
      HOS_Id: 2,
      HOS_EnderecoId: 634,
      Endereco: null,
      HOS_TelefonePS: "11999999999",
      HOS_TelefonePSRamal: null,
      HOS_TelefoneOnco: null,
      HOT_TelefoneOncoRamal: null,
      HOS_Ativo: true,
      HOS_FlagFavorito: false,
      HOS_EnfermeiroReferencia: null,
      HOS_Nome: "Mauricio Teste_1501",
      Log: null,
    },
    CAS_ProcedimentoId: 1,
    Procedimento: {
      PRO_Id: 1,
      PRO_UsuarioCriacaoId: 1,
      UsuarioCriacao: null,
      PRO_UsuarioAlteracaoId: 1,
      UsuarioAlteracao: null,
      PRO_Codigo: "001",
      PRO_Nome: "Outras",
      PRO_Descricao: "Outras",
      PRO_DataCriacao: "2022-01-28T19:51:13.5",
      PRO_DataAlteracao: "2022-01-28T19:53:13.5",
      PRO_Ativo: true,
      Log: null,
    },
    CAS_DescricaoProcedimento: "Procedimento Teste",
    CAS_DescricaoCaso: "Caso Teste Exame",
    CAS_DescricaoAvaliador: null,
    CAS_DataAvaliacao: null,
    CAS_UsuarioAvaliacaoId: null,
    UsuarioAvaliacao: null,
    CAS_Valor: null,
    CAS_DataCriacao: "2022-02-03T00:42:17.863",
    CAS_Ativo: true,
    ListaDocumentos: null,
    tipo: 0,
    Log: null,
  },
  {
    CAS_Id: 3,
    CAS_NumeroSolicitacao: "0000010002",
    CAS_PacienteId: 184,
    Paciente: {
      PAC_Id: 184,
      PAC_UsuarioId: 578,
      Usuario: null,
      PAC_Ativo: true,
      PAC_Prontuario: "123",
      PAC_ObservacaoClinica: "asdasdas",
      PAC_OperadoraId: 6,
      PAC_NumeroCarteirinha: "0181061170000200",
      PAC_DataCriacao: "2021-01-10T00:00:00",
      Log: null,
    },
    CAS_TipoCasoId: 2,
    TipoCaso: {
      TPC_Id: 2,
      TPC_Descricao: "Conta Médica",
      TPC_Ativo: true,
      Log: null,
    },
    CAS_StatusCasoId: 0,
    StatusCaso: {
      STC_Id: 0,
      STC_Descricao: "Analisar",
      STC_Ativo: true,
      Log: null,
    },
    CAS_HospitalId: 2,
    Hospital: {
      HOS_Id: 2,
      HOS_EnderecoId: 634,
      Endereco: null,
      HOS_TelefonePS: "11999999999",
      HOS_TelefonePSRamal: null,
      HOS_TelefoneOnco: null,
      HOT_TelefoneOncoRamal: null,
      HOS_Ativo: true,
      HOS_FlagFavorito: false,
      HOS_EnfermeiroReferencia: null,
      HOS_Nome: "Mauricio Teste_1501",
      Log: null,
    },
    CAS_ProcedimentoId: 1,
    Procedimento: {
      PRO_Id: 1,
      PRO_UsuarioCriacaoId: 1,
      UsuarioCriacao: null,
      PRO_UsuarioAlteracaoId: 1,
      UsuarioAlteracao: null,
      PRO_Codigo: "001",
      PRO_Nome: "Outras",
      PRO_Descricao: "Outras",
      PRO_DataCriacao: "2022-01-28T19:51:13.5",
      PRO_DataAlteracao: "2022-01-28T19:53:13.5",
      PRO_Ativo: true,
      Log: null,
    },
    CAS_DescricaoProcedimento: "Procedimento Teste",
    CAS_DescricaoCaso: "Caso Teste Conta Médica",
    CAS_DescricaoAvaliador: null,
    CAS_DataAvaliacao: null,
    CAS_UsuarioAvaliacaoId: null,
    UsuarioAvaliacao: null,
    CAS_Valor: null,
    CAS_DataCriacao: "2022-02-03T00:42:17.863",
    CAS_Ativo: true,
    ListaDocumentos: null,
    tipo: 0,
    Log: null,
  },
  {
    CAS_Id: 7,
    CAS_NumeroSolicitacao: "0000010003",
    CAS_PacienteId: 184,
    Paciente: {
      PAC_Id: 184,
      PAC_UsuarioId: 578,
      Usuario: null,
      PAC_Ativo: true,
      PAC_Prontuario: "123",
      PAC_ObservacaoClinica: "asdasdas",
      PAC_OperadoraId: 6,
      PAC_NumeroCarteirinha: "0181061170000200",
      PAC_DataCriacao: "2021-01-10T00:00:00",
      Log: null,
    },
    CAS_TipoCasoId: 2,
    TipoCaso: {
      TPC_Id: 2,
      TPC_Descricao: "Conta Médica",
      TPC_Ativo: true,
      Log: null,
    },
    CAS_StatusCasoId: 0,
    StatusCaso: {
      STC_Id: 0,
      STC_Descricao: "Analisar",
      STC_Ativo: true,
      Log: null,
    },
    CAS_HospitalId: null,
    Hospital: null,
    CAS_ProcedimentoId: 4,
    Procedimento: {
      PRO_Id: 4,
      PRO_UsuarioCriacaoId: 1,
      UsuarioCriacao: null,
      PRO_UsuarioAlteracaoId: 1,
      UsuarioAlteracao: null,
      PRO_Codigo: "004",
      PRO_Nome: "Cirurgia de Lombar",
      PRO_Descricao: "Cirurgia de Lombar",
      PRO_DataCriacao: "2022-02-09T00:51:46.367",
      PRO_DataAlteracao: "2022-02-09T00:51:46.367",
      PRO_Ativo: true,
      Log: null,
    },
    CAS_DescricaoProcedimento: "Teste cirurgia de lombar",
    CAS_DescricaoCaso: "",
    CAS_DescricaoAvaliador: null,
    CAS_DataAvaliacao: null,
    CAS_UsuarioAvaliacaoId: null,
    UsuarioAvaliacao: null,
    CAS_Valor: null,
    CAS_DataCriacao: "2022-02-09T15:11:35.753",
    CAS_Ativo: true,
    ListaDocumentos: null,
    tipo: 0,
    Log: null,
  },
  {
    CAS_Id: 8,
    CAS_NumeroSolicitacao: "0000010004",
    CAS_PacienteId: 184,
    Paciente: {
      PAC_Id: 184,
      PAC_UsuarioId: 578,
      Usuario: null,
      PAC_Ativo: true,
      PAC_Prontuario: "123",
      PAC_ObservacaoClinica: "asdasdas",
      PAC_OperadoraId: 6,
      PAC_NumeroCarteirinha: "0181061170000200",
      PAC_DataCriacao: "2021-01-10T00:00:00",
      Log: null,
    },
    CAS_TipoCasoId: 0,
    TipoCaso: {
      TPC_Id: 0,
      TPC_Descricao: "Cirurgia",
      TPC_Ativo: true,
      Log: null,
    },
    CAS_StatusCasoId: 1,
    StatusCaso: {
      STC_Id: 1,
      STC_Descricao: "Em Análise",
      STC_Ativo: true,
      Log: null,
    },
    CAS_HospitalId: 2,
    Hospital: {
      HOS_Id: 2,
      HOS_EnderecoId: 634,
      Endereco: null,
      HOS_TelefonePS: "11999999999",
      HOS_TelefonePSRamal: null,
      HOS_TelefoneOnco: null,
      HOT_TelefoneOncoRamal: null,
      HOS_Ativo: true,
      HOS_FlagFavorito: false,
      HOS_EnfermeiroReferencia: null,
      HOS_Nome: "Mauricio Teste_1501",
      Log: null,
    },
    CAS_ProcedimentoId: 6,
    Procedimento: {
      PRO_Id: 6,
      PRO_UsuarioCriacaoId: 1,
      UsuarioCriacao: null,
      PRO_UsuarioAlteracaoId: 1,
      UsuarioAlteracao: null,
      PRO_Codigo: "006",
      PRO_Nome: "Cirurgia de Coração",
      PRO_Descricao: "Cirurgia de Coração",
      PRO_DataCriacao: "2022-02-09T00:52:11.253",
      PRO_DataAlteracao: "2022-02-09T00:52:11.253",
      PRO_Ativo: true,
      Log: null,
    },
    CAS_DescricaoProcedimento: "Teste procedimento cirurgia de coração",
    CAS_DescricaoCaso: "Teste descrição de caso",
    CAS_DescricaoAvaliador: null,
    CAS_DataAvaliacao: "2022-02-10T00:02:39.203",
    CAS_UsuarioAvaliacaoId: 1,
    UsuarioAvaliacao: {
      USR_Id: 1,
      USR_Email: "master@gmail.com",
      USR_Senha: "waZoWtWDZuc=",
      USR_Ativo: true,
      USR_PessoaId: 3,
      Pessoa: null,
      USR_UnidadeId: 0,
      USR_PrimeiroAcesso: null,
      USR_DeviceID: null,
      USR_TokenRecoveryPassword: null,
      USR_TokenDateExpire: null,
      Log: null,
      sucesso: false,
      mensagemSucesso: null,
      perfilxUsuario: null,
      perfilxSubMenu: null,
      USR_AceitouTermoUso: null,
      USR_AceitouPolitica: null,
      USR_FlagGestor: true,
      USR_FlagContratante: false,
      USR_FlagProfissional: false,
      USR_DataLeituraAvisoCorona: null,
    },
    CAS_Valor: 0,
    CAS_DataCriacao: "2022-02-09T15:36:20.033",
    CAS_Ativo: true,
    ListaDocumentos: null,
    tipo: 0,
    Log: null,
  },
  {
    CAS_Id: 9,
    CAS_NumeroSolicitacao: "0000010005",
    CAS_PacienteId: 184,
    Paciente: {
      PAC_Id: 184,
      PAC_UsuarioId: 578,
      Usuario: null,
      PAC_Ativo: true,
      PAC_Prontuario: "123",
      PAC_ObservacaoClinica: "asdasdas",
      PAC_OperadoraId: 6,
      PAC_NumeroCarteirinha: "0181061170000200",
      PAC_DataCriacao: "2021-01-10T00:00:00",
      Log: null,
    },
    CAS_TipoCasoId: 1,
    TipoCaso: {
      TPC_Id: 1,
      TPC_Descricao: "Exame",
      TPC_Ativo: true,
      Log: null,
    },
    CAS_StatusCasoId: 0,
    StatusCaso: {
      STC_Id: 0,
      STC_Descricao: "Analisar",
      STC_Ativo: true,
      Log: null,
    },
    CAS_HospitalId: null,
    Hospital: null,
    CAS_ProcedimentoId: 3,
    Procedimento: {
      PRO_Id: 3,
      PRO_UsuarioCriacaoId: 1,
      UsuarioCriacao: null,
      PRO_UsuarioAlteracaoId: 1,
      UsuarioAlteracao: null,
      PRO_Codigo: "003",
      PRO_Nome: "Cirurgia de Hernia",
      PRO_Descricao: "Cirurgia de Hernia",
      PRO_DataCriacao: "2022-02-09T00:51:19.197",
      PRO_DataAlteracao: "2022-02-09T00:51:19.197",
      PRO_Ativo: true,
      Log: null,
    },
    CAS_DescricaoProcedimento: "Teste cirurgia de hernia.",
    CAS_DescricaoCaso: "Descrição do caso",
    CAS_DescricaoAvaliador: null,
    CAS_DataAvaliacao: null,
    CAS_UsuarioAvaliacaoId: null,
    UsuarioAvaliacao: null,
    CAS_Valor: null,
    CAS_DataCriacao: "2022-02-09T22:14:26.32",
    CAS_Ativo: true,
    ListaDocumentos: null,
    tipo: 0,
    Log: null,
  },
  {
    CAS_Id: 10,
    CAS_NumeroSolicitacao: "0000010006",
    CAS_PacienteId: 185,
    Paciente: {
      PAC_Id: 185,
      PAC_UsuarioId: 582,
      Usuario: null,
      PAC_Ativo: true,
      PAC_Prontuario: "",
      PAC_ObservacaoClinica: "",
      PAC_OperadoraId: 0,
      PAC_NumeroCarteirinha: null,
      PAC_DataCriacao: null,
      Log: null,
    },
    CAS_TipoCasoId: 0,
    TipoCaso: {
      TPC_Id: 0,
      TPC_Descricao: "Cirurgia",
      TPC_Ativo: true,
      Log: null,
    },
    CAS_StatusCasoId: 0,
    StatusCaso: {
      STC_Id: 0,
      STC_Descricao: "Analisar",
      STC_Ativo: true,
      Log: null,
    },
    CAS_HospitalId: null,
    Hospital: null,
    CAS_ProcedimentoId: 6,
    Procedimento: {
      PRO_Id: 6,
      PRO_UsuarioCriacaoId: 1,
      UsuarioCriacao: null,
      PRO_UsuarioAlteracaoId: 1,
      UsuarioAlteracao: null,
      PRO_Codigo: "006",
      PRO_Nome: "Cirurgia de Coração",
      PRO_Descricao: "Cirurgia de Coração",
      PRO_DataCriacao: "2022-02-09T00:52:11.253",
      PRO_DataAlteracao: "2022-02-09T00:52:11.253",
      PRO_Ativo: true,
      Log: null,
    },
    CAS_DescricaoProcedimento: "Teste cirurgia de coração",
    CAS_DescricaoCaso: "",
    CAS_DescricaoAvaliador: null,
    CAS_DataAvaliacao: null,
    CAS_UsuarioAvaliacaoId: null,
    UsuarioAvaliacao: null,
    CAS_Valor: null,
    CAS_DataCriacao: "2022-02-10T13:26:22.263",
    CAS_Ativo: true,
    ListaDocumentos: null,
    tipo: 0,
    Log: null,
  },
  {
    CAS_Id: 11,
    CAS_NumeroSolicitacao: "0000010007",
    CAS_PacienteId: 186,
    Paciente: {
      PAC_Id: 186,
      PAC_UsuarioId: 583,
      Usuario: null,
      PAC_Ativo: true,
      PAC_Prontuario: "",
      PAC_ObservacaoClinica: "",
      PAC_OperadoraId: 0,
      PAC_NumeroCarteirinha: null,
      PAC_DataCriacao: null,
      Log: null,
    },
    CAS_TipoCasoId: 1,
    TipoCaso: {
      TPC_Id: 1,
      TPC_Descricao: "Exame",
      TPC_Ativo: true,
      Log: null,
    },
    CAS_StatusCasoId: 0,
    StatusCaso: {
      STC_Id: 0,
      STC_Descricao: "Analisar",
      STC_Ativo: true,
      Log: null,
    },
    CAS_HospitalId: null,
    Hospital: null,
    CAS_ProcedimentoId: 1,
    Procedimento: {
      PRO_Id: 1,
      PRO_UsuarioCriacaoId: 1,
      UsuarioCriacao: null,
      PRO_UsuarioAlteracaoId: 1,
      UsuarioAlteracao: null,
      PRO_Codigo: "001",
      PRO_Nome: "Outras",
      PRO_Descricao: "Outras",
      PRO_DataCriacao: "2022-01-28T19:51:13.5",
      PRO_DataAlteracao: "2022-01-28T19:53:13.5",
      PRO_Ativo: true,
      Log: null,
    },
    CAS_DescricaoProcedimento: "Teste para fazer exame",
    CAS_DescricaoCaso: "Descrição do caso",
    CAS_DescricaoAvaliador: null,
    CAS_DataAvaliacao: null,
    CAS_UsuarioAvaliacaoId: null,
    UsuarioAvaliacao: null,
    CAS_Valor: null,
    CAS_DataCriacao: "2022-02-10T15:03:33.103",
    CAS_Ativo: true,
    ListaDocumentos: null,
    tipo: 0,
    Log: null,
  },
  {
    CAS_Id: 12,
    CAS_NumeroSolicitacao: "0000010008",
    CAS_PacienteId: 187,
    Paciente: {
      PAC_Id: 187,
      PAC_UsuarioId: 584,
      Usuario: null,
      PAC_Ativo: true,
      PAC_Prontuario: "",
      PAC_ObservacaoClinica: "",
      PAC_OperadoraId: 0,
      PAC_NumeroCarteirinha: null,
      PAC_DataCriacao: null,
      Log: null,
    },
    CAS_TipoCasoId: 2,
    TipoCaso: {
      TPC_Id: 2,
      TPC_Descricao: "Conta Médica",
      TPC_Ativo: true,
      Log: null,
    },
    CAS_StatusCasoId: 0,
    StatusCaso: {
      STC_Id: 0,
      STC_Descricao: "Analisar",
      STC_Ativo: true,
      Log: null,
    },
    CAS_HospitalId: null,
    Hospital: null,
    CAS_ProcedimentoId: 2,
    Procedimento: {
      PRO_Id: 2,
      PRO_UsuarioCriacaoId: 1,
      UsuarioCriacao: null,
      PRO_UsuarioAlteracaoId: 1,
      UsuarioAlteracao: null,
      PRO_Codigo: "002",
      PRO_Nome: "Cirurgia de Catarata",
      PRO_Descricao: "Cirurgia de Catarata",
      PRO_DataCriacao: "2022-02-09T00:50:57.543",
      PRO_DataAlteracao: "2022-02-09T00:50:57.543",
      PRO_Ativo: true,
      Log: null,
    },
    CAS_DescricaoProcedimento: "Cirurgia de Catarata",
    CAS_DescricaoCaso: "Descrição de caso.",
    CAS_DescricaoAvaliador: null,
    CAS_DataAvaliacao: null,
    CAS_UsuarioAvaliacaoId: null,
    UsuarioAvaliacao: null,
    CAS_Valor: null,
    CAS_DataCriacao: "2022-02-13T12:56:55.517",
    CAS_Ativo: true,
    ListaDocumentos: null,
    tipo: 0,
    Log: null,
  },
  {
    CAS_Id: 13,
    CAS_NumeroSolicitacao: "0000010009",
    CAS_PacienteId: 188,
    Paciente: {
      PAC_Id: 188,
      PAC_UsuarioId: 585,
      Usuario: null,
      PAC_Ativo: true,
      PAC_Prontuario: "",
      PAC_ObservacaoClinica: "",
      PAC_OperadoraId: 0,
      PAC_NumeroCarteirinha: null,
      PAC_DataCriacao: null,
      Log: null,
    },
    CAS_TipoCasoId: 0,
    TipoCaso: {
      TPC_Id: 0,
      TPC_Descricao: "Cirurgia",
      TPC_Ativo: true,
      Log: null,
    },
    CAS_StatusCasoId: 0,
    StatusCaso: {
      STC_Id: 0,
      STC_Descricao: "Analisar",
      STC_Ativo: true,
      Log: null,
    },
    CAS_HospitalId: null,
    Hospital: null,
    CAS_ProcedimentoId: 4,
    Procedimento: {
      PRO_Id: 4,
      PRO_UsuarioCriacaoId: 1,
      UsuarioCriacao: null,
      PRO_UsuarioAlteracaoId: 1,
      UsuarioAlteracao: null,
      PRO_Codigo: "004",
      PRO_Nome: "Cirurgia de Lombar",
      PRO_Descricao: "Cirurgia de Lombar",
      PRO_DataCriacao: "2022-02-09T00:51:46.367",
      PRO_DataAlteracao: "2022-02-09T00:51:46.367",
      PRO_Ativo: true,
      Log: null,
    },
    CAS_DescricaoProcedimento: "Teste teste teste Teste teste teste Teste teste teste...",
    CAS_DescricaoCaso:
      "Teste teste teste Teste teste teste Teste teste teste...\nTeste teste teste Teste teste teste Teste teste teste...\nTeste teste teste Teste teste teste Teste teste teste...",
    CAS_DescricaoAvaliador: null,
    CAS_DataAvaliacao: null,
    CAS_UsuarioAvaliacaoId: null,
    UsuarioAvaliacao: null,
    CAS_Valor: null,
    CAS_DataCriacao: "2022-02-13T13:50:30.187",
    CAS_Ativo: true,
    ListaDocumentos: null,
    tipo: 0,
    Log: null,
  },
  {
    CAS_Id: 14,
    CAS_NumeroSolicitacao: "0000010010",
    CAS_PacienteId: 189,
    Paciente: {
      PAC_Id: 189,
      PAC_UsuarioId: 586,
      Usuario: null,
      PAC_Ativo: true,
      PAC_Prontuario: "",
      PAC_ObservacaoClinica: "",
      PAC_OperadoraId: 0,
      PAC_NumeroCarteirinha: null,
      PAC_DataCriacao: null,
      Log: null,
    },
    CAS_TipoCasoId: 1,
    TipoCaso: {
      TPC_Id: 1,
      TPC_Descricao: "Exame",
      TPC_Ativo: true,
      Log: null,
    },
    CAS_StatusCasoId: 0,
    StatusCaso: {
      STC_Id: 0,
      STC_Descricao: "Analisar",
      STC_Ativo: true,
      Log: null,
    },
    CAS_HospitalId: null,
    Hospital: null,
    CAS_ProcedimentoId: 5,
    Procedimento: {
      PRO_Id: 5,
      PRO_UsuarioCriacaoId: 1,
      UsuarioCriacao: null,
      PRO_UsuarioAlteracaoId: 1,
      UsuarioAlteracao: null,
      PRO_Codigo: "005",
      PRO_Nome: "Cirurgia de Coluna",
      PRO_Descricao: "Cirurgia de Coluna",
      PRO_DataCriacao: "2022-02-09T00:51:58.457",
      PRO_DataAlteracao: "2022-02-09T00:51:58.457",
      PRO_Ativo: true,
      Log: null,
    },
    CAS_DescricaoProcedimento: "Teste teste teste...\nTeste teste teste...\nTeste teste teste...\nTeste teste teste...",
    CAS_DescricaoCaso: "Teste teste teste... Teste teste teste... Teste teste teste... Teste teste teste...",
    CAS_DescricaoAvaliador: null,
    CAS_DataAvaliacao: null,
    CAS_UsuarioAvaliacaoId: null,
    UsuarioAvaliacao: null,
    CAS_Valor: null,
    CAS_DataCriacao: "2022-02-13T13:56:36.09",
    CAS_Ativo: true,
    ListaDocumentos: null,
    tipo: 0,
    Log: null,
  },
  {
    CAS_Id: 18,
    CAS_NumeroSolicitacao: "0000010011",
    CAS_PacienteId: 191,
    Paciente: {
      PAC_Id: 191,
      PAC_UsuarioId: 587,
      Usuario: null,
      PAC_Ativo: true,
      PAC_Prontuario: "",
      PAC_ObservacaoClinica: "",
      PAC_OperadoraId: 0,
      PAC_NumeroCarteirinha: null,
      PAC_DataCriacao: null,
      Log: null,
    },
    CAS_TipoCasoId: 1,
    TipoCaso: {
      TPC_Id: 1,
      TPC_Descricao: "Exame",
      TPC_Ativo: true,
      Log: null,
    },
    CAS_StatusCasoId: 0,
    StatusCaso: {
      STC_Id: 0,
      STC_Descricao: "Analisar",
      STC_Ativo: true,
      Log: null,
    },
    CAS_HospitalId: null,
    Hospital: null,
    CAS_ProcedimentoId: 6,
    Procedimento: {
      PRO_Id: 6,
      PRO_UsuarioCriacaoId: 1,
      UsuarioCriacao: null,
      PRO_UsuarioAlteracaoId: 1,
      UsuarioAlteracao: null,
      PRO_Codigo: "006",
      PRO_Nome: "Cirurgia de Coração",
      PRO_Descricao: "Cirurgia de Coração",
      PRO_DataCriacao: "2022-02-09T00:52:11.253",
      PRO_DataAlteracao: "2022-02-09T00:52:11.253",
      PRO_Ativo: true,
      Log: null,
    },
    CAS_DescricaoProcedimento: "Teste cirurgia de coração",
    CAS_DescricaoCaso: "Teste descrição do caso da Eva",
    CAS_DescricaoAvaliador: null,
    CAS_DataAvaliacao: null,
    CAS_UsuarioAvaliacaoId: null,
    UsuarioAvaliacao: null,
    CAS_Valor: null,
    CAS_DataCriacao: "2022-02-14T16:32:14.11",
    CAS_Ativo: true,
    ListaDocumentos: null,
    tipo: 0,
    Log: null,
  },
  {
    CAS_Id: 19,
    CAS_NumeroSolicitacao: "0000010012",
    CAS_PacienteId: 192,
    Paciente: {
      PAC_Id: 192,
      PAC_UsuarioId: 588,
      Usuario: null,
      PAC_Ativo: true,
      PAC_Prontuario: "",
      PAC_ObservacaoClinica: "",
      PAC_OperadoraId: 0,
      PAC_NumeroCarteirinha: null,
      PAC_DataCriacao: null,
      Log: null,
    },
    CAS_TipoCasoId: 0,
    TipoCaso: {
      TPC_Id: 0,
      TPC_Descricao: "Cirurgia",
      TPC_Ativo: true,
      Log: null,
    },
    CAS_StatusCasoId: 0,
    StatusCaso: {
      STC_Id: 0,
      STC_Descricao: "Analisar",
      STC_Ativo: true,
      Log: null,
    },
    CAS_HospitalId: null,
    Hospital: null,
    CAS_ProcedimentoId: 6,
    Procedimento: {
      PRO_Id: 6,
      PRO_UsuarioCriacaoId: 1,
      UsuarioCriacao: null,
      PRO_UsuarioAlteracaoId: 1,
      UsuarioAlteracao: null,
      PRO_Codigo: "006",
      PRO_Nome: "Cirurgia de Coração",
      PRO_Descricao: "Cirurgia de Coração",
      PRO_DataCriacao: "2022-02-09T00:52:11.253",
      PRO_DataAlteracao: "2022-02-09T00:52:11.253",
      PRO_Ativo: true,
      Log: null,
    },
    CAS_DescricaoProcedimento: "Teste Descrição",
    CAS_DescricaoCaso: "Teste Descrição Caso",
    CAS_DescricaoAvaliador: null,
    CAS_DataAvaliacao: null,
    CAS_UsuarioAvaliacaoId: null,
    UsuarioAvaliacao: null,
    CAS_Valor: null,
    CAS_DataCriacao: "2022-02-15T23:24:08.1",
    CAS_Ativo: true,
    ListaDocumentos: null,
    tipo: 0,
    Log: null,
  },
];
